import type { ChecklistTemplate, Expert, InspectionOrder, SelectionOrder, Tariff, ChatThread } from '../types';
import type { Candidate, LegalCheck } from '../types';

export const mockExperts: Expert[] = [
  {
    id: 'eva',
    name: 'Ева Лисова',
    phone: '+7 (900) 111-22-33',
    email: 'eva@example.com',
    cities: ['Москва', 'Долгопрудный'],
    brands: ['BMW', 'Volkswagen', 'Ford'],
    rating: 4.8,
    completedInspections: 184,
    cancelRate: 6,
    active: true,
    notes: 'Сильна в VAG и американцах',
    specialization: 'body',
    services: ['inspection', 'selection'],
    travelRadiusKm: 40,
    baseArea: 'Москва (север)',
    brandTags: ['BMW', 'VAG', 'Ford'],
    skillTags: ['Толщиномер', 'Диагностика сканером', 'Выезд на сделку'],
    loadToday: 'busy',
    avgReportHours: 5,
    avgResponseMinutes: 12,
    last30dInspections: 26,
    recommendRatio: 0.82,
  },
  {
    id: 'evk',
    name: 'Евгения К.',
    phone: '+7 (901) 004-22-55',
    email: 'evk@example.com',
    cities: ['Москва'],
    brands: ['Geely', 'Haval', 'Chery'],
    rating: 4.6,
    completedInspections: 120,
    cancelRate: 9,
    active: true,
    specialization: 'electric',
    services: ['inspection', 'selection', 'deal_support'],
    travelRadiusKm: 25,
    baseArea: 'Москва (центр)',
    brandTags: ['Geely', 'Haval', 'Chery', 'EV'],
    skillTags: ['Гибриды/EV', 'Диагностика сканером'],
    loadToday: 'free',
    avgReportHours: 8,
    avgResponseMinutes: 20,
    last30dInspections: 18,
    recommendRatio: 0.76,
  },
  {
    id: 'denis',
    name: 'Денис К.',
    phone: '+7 (926) 112-05-10',
    cities: ['Москва'],
    brands: ['Ford', 'Toyota', 'Kia'],
    rating: 4.4,
    completedInspections: 95,
    cancelRate: 11,
    active: false,
    specialization: 'engine',
    services: ['inspection'],
    travelRadiusKm: 60,
    baseArea: 'Москва (юг)',
    brandTags: ['Ford', 'Toyota', 'Kia'],
    skillTags: ['Моторист', 'Перекупская оценка'],
    loadToday: 'overloaded',
    avgReportHours: 10,
    avgResponseMinutes: 35,
    last30dInspections: 12,
    recommendRatio: 0.71,
  },
];

export const mockInspections: InspectionOrder[] = [
  {
    id: 'OSM-1001',
    status: 'WAITING_FOR_EXPERT',
    sourceUrl: 'https://auto.ru/car1',
    parsedData: { make: 'Ford', model: 'Explorer', year: 2019, mileage: 58000, price: 3300000, city: 'Москва' },
    city: 'Москва',
    client: { name: 'Денис', phone: '+7 (996) 112-05-10' },
    sellerContact: '+7 (900) 777-33-22',
    priceSegment: '3–3.5 млн ₽',
    summary: 'Пробег честный, смотреть раму, рулевую и ЛКП по крыше',
    expertId: 'denis',
    appointmentAt: '2025-11-21T11:40:00Z',
    createdAt: '2025-11-20T16:50:00Z',
    updatedAt: '2025-11-20T16:50:00Z',
    address: 'Москва, Алтуфьевское шоссе, 31с1',
  },
  {
    id: 'OSM-1002',
    status: 'ASSIGNED',
    sourceUrl: 'https://auto.ru/car2',
    parsedData: { make: 'Chery', model: 'Tiggo 7 Pro Max', year: 2023, mileage: 12000, price: 2100000, city: 'Москва' },
    city: 'Москва',
    client: { name: 'Илья', phone: '+7 (928) 155-48-48' },
    priceSegment: '2–2.5 млн ₽',
    summary: 'Важно: коробка, шумы подвески, сход-развал',
    expertId: 'evk',
    appointmentAt: '2025-11-21T14:35:00Z',
    createdAt: '2025-11-20T16:54:00Z',
    updatedAt: '2025-11-20T16:54:00Z',
    selectionOrderId: 'POD-0501',
    address: 'Москва, Новоясеневский проезд 15А',
  },
  {
    id: 'OSM-1003',
    status: 'IN_PROGRESS',
    sourceUrl: 'https://auto.ru/car3',
    parsedData: { make: 'Geely', model: 'Tugella', year: 2021, mileage: 41000, price: 2400000, city: 'Москва' },
    city: 'Москва',
    client: { name: 'Кавур Маким', phone: '+7 (963) 647-70-94' },
    priceSegment: '2–2.5 млн ₽',
    summary: 'Смотреть вариатор, турбину, проверить ДТП по базам',
    expertId: 'eva',
    appointmentAt: '2025-11-21T14:30:00Z',
    createdAt: '2025-11-20T16:52:00Z',
    updatedAt: '2025-11-20T16:52:00Z',
    selectionOrderId: 'POD-0501',
    address: 'Москва, Старопотаповская улица 41',
  },
  {
    id: 'OSM-1004',
    status: 'DONE',
    sourceUrl: 'https://auto.ru/car4',
    parsedData: { make: 'Toyota', model: 'Highlander', year: 2020, mileage: 76000, price: 3550000, city: 'Голицыно' },
    city: 'Голицыно',
    client: { name: 'Михтар Грам', phone: '+7 (917) 461-16-16' },
    priceSegment: '3–3.5 млн ₽',
    summary: 'Усиленно проверить ГРМ и историю сервисного',
    expertId: 'evk',
    appointmentAt: '2025-11-21T12:20:00Z',
    createdAt: '2025-11-20T16:49:00Z',
    updatedAt: '2025-11-20T16:49:00Z',
    address: 'Голицыно, Промышленный проезд, вл2с1',
    report: {
      id: 'REP-9001',
      inspectionOrderId: 'OSM-1004',
      templateId: 'CHK-1',
      data: {},
      summary: 'Рекомендуем, есть следы перекраса крыла, тех.часть в норме',
      recommendedDiscount: { min: 60000, max: 90000, comment: 'Крыло + полировка + мелкие вложения' },
      webUrl: 'https://reports.local/OSM-1004',
      pdfUrl: 'https://reports.local/OSM-1004.pdf',
    },
  },
];

const candidateLegalOk: LegalCheck = {
  pledge: 'OK',
  restrictions: 'OK',
  fines: 'OK',
  ownersCount: 1,
  notes: 'ДКП и сервиска в наличии',
};

const candidateLegalRisk: LegalCheck = {
  pledge: 'RISK',
  restrictions: 'RISK',
  fines: 'OK',
  ownersCount: 3,
  notes: 'Есть залог, нужно уточнять погашение',
};

const mockCandidates: Candidate[] = [
  {
    id: 'CAND-1',
    sourceUrl: 'https://auto.ru/car2',
    make: 'Chery',
    model: 'Tiggo 7 Pro Max',
    year: 2023,
    body: 'SUV',
    mileage: 12000,
    price: 2100000,
    city: 'Москва',
    status: 'PENDING',
    summary: 'Свежий, 1 владелец, ТО у дилера',
    inspectionId: 'OSM-1002',
    legalCheck: candidateLegalOk,
  },
  {
    id: 'CAND-2',
    sourceUrl: 'https://auto.ru/car3',
    make: 'Geely',
    model: 'Tugella',
    year: 2021,
    body: 'SUV',
    mileage: 41000,
    price: 2400000,
    city: 'Москва',
    status: 'APPROVED',
    summary: 'Есть вопросы по вариатору, но по ЛКП чисто',
    inspectionId: 'OSM-1003',
    legalCheck: candidateLegalRisk,
  },
  {
    id: 'CAND-3',
    sourceUrl: 'https://auto.ru/car5',
    make: 'Kia',
    model: 'Seltos',
    year: 2020,
    body: 'SUV',
    mileage: 38000,
    price: 1850000,
    city: 'Москва',
    status: 'REJECTED',
    summary: 'Дороговато, механика',
  },
];

export const mockSelections: SelectionOrder[] = [
  {
    id: 'POD-0501',
    status: 'CANDIDATES_SENT',
    city: 'Москва',
    cityFrom: 'Москва',
    cityTarget: 'Москва и МО',
    client: { name: 'Илья', phone: '+7 (928) 155-48-48' },
    budget: '2.5–3 млн ₽',
    budgetMin: 2500000,
    budgetMax: 3000000,
    requirements: 'Кроссовер, 2020+, до 70 тыс. км, без серьёзных ДТП, автомат',
    deadline: '2025-12-05',
    includedInspections: 5,
    extraInspections: 0,
    tariffId: 'P-SEL-1',
    inspectionIds: ['OSM-1002', 'OSM-1003'],
    candidates: mockCandidates,
    createdAt: '2025-11-15T10:00:00Z',
    updatedAt: '2025-11-20T16:54:00Z',
  },
];

export const mockChecklistTemplates: ChecklistTemplate[] = [
  {
    id: 'CHK-1',
    name: 'Базовый чеклист: легковой авто',
    version: '1.1',
    sections: [
      {
        id: 'body',
        title: 'Кузов и ЛКП',
        items: [
          { id: 'paint', label: 'Толщина ЛКП (замеры)', type: 'text', severityEnabled: true },
          {
            id: 'accident',
            label: 'Следы ДТП/ремонт',
            type: 'enum',
            options: [
              { value: 'no', label: 'Не обнаружено' },
              { value: 'minor', label: 'Косметический ремонт' },
              { value: 'serious', label: 'Серьёзные повреждения' },
            ],
            severityEnabled: true,
          },
          { id: 'corrosion', label: 'Коррозия/очаги', type: 'enum', options: [{ value: 'no', label: 'Нет' }, { value: 'surface', label: 'Поверхностная' }, { value: 'structural', label: 'Несущие элементы' }], severityEnabled: true },
          { id: 'glass', label: 'Стёкла/оптика заменялись', type: 'enum', options: [{ value: 'no', label: 'Нет' }, { value: 'partial', label: 'Частично' }, { value: 'yes', label: 'Да' }] },
        ],
      },
      {
        id: 'engine',
        title: 'Двигатель и охлаждение',
        items: [
          { id: 'engine-sound', label: 'Посторонние звуки', type: 'enum', options: [{ value: 'ok', label: 'Нет' }, { value: 'warn', label: 'Есть' }], severityEnabled: true },
          { id: 'leaks', label: 'Подтеки масел/антифриза', type: 'enum', options: [{ value: 'no', label: 'Нет' }, { value: 'minor', label: 'Незначительные' }, { value: 'yes', label: 'Есть' }], severityEnabled: true },
          { id: 'fluids', label: 'Уровни жидкостей', type: 'enum', options: [{ value: 'ok', label: 'OK' }, { value: 'low', label: 'Ниже нормы' }] },
          { id: 'belts', label: 'Ремни/цепь/помпа', type: 'text' },
        ],
      },
      {
        id: 'suspension',
        title: 'Трансмиссия и ходовая',
        items: [
          { id: 'transmission', label: 'Трансмиссия (АКПП/МКПП/вариатор)', type: 'enum', options: [{ value: 'ok', label: 'Ок' }, { value: 'jerk', label: 'Пинки/рывки' }, { value: 'slip', label: 'Пробуксовка' }], severityEnabled: true },
          { id: 'suspension-noise', label: 'Подвеска/шуми', type: 'enum', options: [{ value: 'ok', label: 'Без шумов' }, { value: 'minor', label: 'Есть посторонние звуки' }], severityEnabled: true },
          { id: 'steering', label: 'Рулевое/люфт', type: 'enum', options: [{ value: 'ok', label: 'Норма' }, { value: 'play', label: 'Есть люфт/стук' }], severityEnabled: true },
          { id: 'brakes', label: 'Тормоза', type: 'enum', options: [{ value: 'ok', label: 'Норма' }, { value: 'vibration', label: 'Вибрации' }, { value: 'pull', label: 'Ведёт/увод' }], severityEnabled: true },
        ],
      },
      {
        id: 'interior',
        title: 'Электрика и салон',
        items: [
          { id: 'diagnostics', label: 'Ошибки на сканере', type: 'enum', options: [{ value: 'clean', label: 'Нет ошибок' }, { value: 'minor', label: 'Несистемные' }, { value: 'critical', label: 'Критичные' }] },
          { id: 'climate', label: 'Климат/печка/кондиционер', type: 'enum', options: [{ value: 'ok', label: 'Работает' }, { value: 'weak', label: 'Слабое охлаждение/обогрев' }, { value: 'no', label: 'Не работает' }] },
          { id: 'multimedia', label: 'Мультимедиа/камеры', type: 'enum', options: [{ value: 'ok', label: 'Работает' }, { value: 'partial', label: 'Частично' }, { value: 'no', label: 'Не работает' }] },
          { id: 'interior', label: 'Состояние салона', type: 'text' },
        ],
      },
      {
        id: 'docs',
        title: 'Документы и история',
        items: [
          { id: 'vin-match', label: 'VIN/маркировки совпадают', type: 'enum', options: [{ value: 'ok', label: 'Да' }, { value: 'issue', label: 'Есть вопросы' }] },
          { id: 'owners', label: 'Кол-во владельцев (ПТС)', type: 'number' },
          { id: 'service', label: 'Сервисная история', type: 'text' },
        ],
      },
      {
        id: 'testdrive',
        title: 'Тест-драйв',
        items: [
          { id: 'dynamics', label: 'Динамика/разгон', type: 'enum', options: [{ value: 'ok', label: 'Норма' }, { value: 'sluggish', label: 'Вялая' }, { value: 'issues', label: 'Есть проблемы' }] },
          { id: 'vibrations', label: 'Вибрации/шумы при ходе', type: 'enum', options: [{ value: 'no', label: 'Нет' }, { value: 'yes', label: 'Есть' }] },
          { id: 'summary-notes', label: 'Замечания по пробной поездке', type: 'text' },
        ],
      },
    ],
  },
];

export const mockTariffs: Tariff[] = [
  { id: 'T-1', priceSegment: 'до 1.5 млн ₽', amount: 9000, comment: 'Город внутри МКАД', kind: 'inspection' },
  { id: 'T-2', priceSegment: '1.5–3 млн ₽', amount: 12000, comment: 'Включая выезд до 30 км', kind: 'inspection' },
  { id: 'T-3', priceSegment: '3–5 млн ₽', amount: 'custom', comment: 'По договоренности', kind: 'inspection' },
  { id: 'P-SEL-1', priceSegment: 'Комплексный подбор (5 осмотров)', amount: 45000, comment: 'Базовый пакет 5 осмотров', kind: 'selection' },
  { id: 'P-SEL-2', priceSegment: 'Комплексный подбор (доп. осмотр)', amount: 9000, comment: 'Добавочный осмотр к подбору', kind: 'selection' },
];

export const mockChats: ChatThread[] = [
  {
    id: 'CHAT-ILYA',
    participant: { name: 'Илья', phone: '+7 (928) 155-48-48' },
    selectionId: 'POD-0501',
    inspectionId: 'OSM-1002',
    messages: [
      { id: 'm0', from: 'system', text: 'Создан осмотр OSM-1002, назначение эксперта ожидается.', createdAt: '2025-11-20T16:58:00Z', actions: [{ label: 'Открыть осмотр', reply: 'Открыл карточку осмотра.' }] },
      { id: 'm1', from: 'client', text: 'Привет! Когда примерно осмотр?', createdAt: '2025-11-20T17:00:00Z' },
      { id: 'm2', from: 'service', text: 'Назначили на 21.11 14:35, эксперт уже закреплён.', createdAt: '2025-11-20T17:05:00Z', actions: [{ label: 'Согласовать время', reply: 'Пожалуйста, подтвердите 21.11 14:35 или предложите другое окно.' }] },
      { id: 'm3', from: 'client', text: 'Ок, жду отчёт до вечера.', createdAt: '2025-11-20T17:06:00Z' },
      { id: 'm6', from: 'system', text: 'Отчёт по OSM-1002 готов. Рекомендована скидка 60–90 тыс.', createdAt: '2025-11-21T18:30:00Z', actions: [{ label: 'Открыть отчёт', reply: 'Вот ссылка на отчёт: https://reports.local/OSM-1002' }] },
    ],
  },
  {
    id: 'CHAT-DENIS',
    participant: { name: 'Денис', phone: '+7 (996) 112-05-10' },
    inspectionId: 'OSM-1001',
    messages: [
      { id: 'm4', from: 'client', text: 'Скинул продавца, телефон в карточке.', createdAt: '2025-11-20T17:10:00Z' },
      { id: 'm5', from: 'service', text: 'Взяли в работу, сверимся по времени.', createdAt: '2025-11-20T17:12:00Z' },
      { id: 'm7', from: 'system', text: 'Слот подтверждён: 21.11, 11:40. Эксперт: Денис К.', createdAt: '2025-11-20T17:20:00Z', actions: [{ label: 'Перенести', reply: 'Предлагаю альтернативу: 21.11 12:30 или 22.11 10:00' }] },
    ],
  },
];
