import type { ChecklistTemplate, Expert, InspectionOrder, SelectionOrder, Tariff, ChatThread } from '../types';
import type { Candidate, LegalCheck } from '../types';

export const mockExperts: Expert[] = [
  {
    id: 'eva',
    name: 'Ева Лисова',
    phone: '+7 (900) 111-22-33',
    email: 'eva@example.com',
    cities: ['Москва', 'Долгопрудный'],
    brands: ['BMW', 'Volkswagen', 'Ford'],
    rating: 4.8,
    completedInspections: 184,
    cancelRate: 6,
    active: true,
    notes: 'Сильна в VAG и американцах',
    specialization: 'body',
    services: ['inspection', 'selection'],
    travelRadiusKm: 40,
    baseArea: 'Москва (север)',
    brandTags: ['BMW', 'VAG', 'Ford'],
    skillTags: ['Толщиномер', 'Диагностика сканером', 'Выезд на сделку'],
    loadToday: 'busy',
    avgReportHours: 5,
    avgResponseMinutes: 12,
    last30dInspections: 26,
    recommendRatio: 0.82,
  },
  {
    id: 'evk',
    name: 'Евгения К.',
    phone: '+7 (901) 004-22-55',
    email: 'evk@example.com',
    cities: ['Москва'],
    brands: ['Geely', 'Haval', 'Chery'],
    rating: 4.6,
    completedInspections: 120,
    cancelRate: 9,
    active: true,
    specialization: 'electric',
    services: ['inspection', 'selection', 'deal_support'],
    travelRadiusKm: 25,
    baseArea: 'Москва (центр)',
    brandTags: ['Geely', 'Haval', 'Chery', 'EV'],
    skillTags: ['Гибриды/EV', 'Диагностика сканером'],
    loadToday: 'free',
    avgReportHours: 8,
    avgResponseMinutes: 20,
    last30dInspections: 18,
    recommendRatio: 0.76,
  },
  {
    id: 'denis',
    name: 'Денис К.',
    phone: '+7 (926) 112-05-10',
    cities: ['Москва'],
    brands: ['Ford', 'Toyota', 'Kia'],
    rating: 4.4,
    completedInspections: 95,
    cancelRate: 11,
    active: false,
    specialization: 'engine',
    services: ['inspection'],
    travelRadiusKm: 60,
    baseArea: 'Москва (юг)',
    brandTags: ['Ford', 'Toyota', 'Kia'],
    skillTags: ['Моторист', 'Перекупская оценка'],
    loadToday: 'overloaded',
    avgReportHours: 10,
    avgResponseMinutes: 35,
    last30dInspections: 12,
    recommendRatio: 0.71,
  },
];

export const mockInspections: InspectionOrder[] = [
  {
    id: 'OSM-2001',
    status: 'DONE',
    sourceUrl: 'https://auto.ru/car-ford-explorer-2019',
    parsedData: { make: 'Ford', model: 'Explorer', year: 2019, mileage: 58200, price: 3300000, city: 'Москва' },
    city: 'Москва',
    client: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    sellerContact: '+7 (900) 777-33-22',
    priceSegment: '3–3.5 млн ₽',
    summary: 'Пробег честный, смотреть раму, рулевую и ЛКП по крыше',
    expertId: 'denis',
    appointmentAt: '2025-12-02T11:40:00Z',
    createdAt: '2025-12-01T09:10:00Z',
    updatedAt: '2025-12-02T18:05:00Z',
    address: 'Москва, Алтуфьевское шоссе, 31с1',
    selectionOrderId: 'POD-0601',
    report: {
      id: 'REP-1001',
      inspectionOrderId: 'OSM-2001',
      templateId: 'CHK-1',
      data: {
        body: {
          paint: '120–165 мкм по кругу, крыша 180 мкм (косметика)',
          accident: 'minor',
          corrosion: 'surface',
          glass: 'partial',
        },
        engine: {
          'engine-sound': 'warn',
          leaks: 'minor',
          fluids: 'ok',
          belts: 'Замена ремня через 10–15 тыс. км',
        },
        suspension: {
          transmission: 'jerk',
          'suspension-noise': 'minor',
          steering: 'ok',
          brakes: 'vibration',
        },
        interior: {
          diagnostics: 'minor',
          climate: 'ok',
          multimedia: 'partial',
          interior: 'Следы носки руля/сидений, без дыр/порезов',
        },
        docs: {
          'vin-match': 'ok',
          owners: 2,
          service: 'ТО у дилера до 70 тыс., дальше частично у частника',
        },
        testdrive: {
          dynamics: 'sluggish',
          vibrations: 'yes',
          'summary-notes': 'Вибрации на 110 км/ч, вероятно баланс/резина',
        },
      },
      severities: {
        accident: 'WARN',
        corrosion: 'WARN',
        'engine-sound': 'WARN',
        leaks: 'WARN',
        transmission: 'WARN',
        'suspension-noise': 'WARN',
        brakes: 'WARN',
      },
      summary: 'Рекомендуем с оговорками: косметический окрас крыши, лёгкие течи, есть пинки АКПП и вибрации на скорости.',
      recommendedDiscount: { min: 60000, max: 90000, comment: 'Окрас/полировка, баланс + возможные работы по АКПП' },
      webUrl: 'https://reports.local/OSM-2001',
      pdfUrl: 'https://reports.local/OSM-2001.pdf',
      legalCheck: {
        pledge: 'OK',
        restrictions: 'OK',
        fines: 'OK',
        ownersCount: 2,
        notes: 'ПТС оригинал, ограничения не выявлены',
      },
    },
  },
  {
    id: 'OSM-2002',
    status: 'REPORT_IN_PROGRESS',
    sourceUrl: 'https://auto.ru/car-chery-tiggo7-2023',
    parsedData: { make: 'Chery', model: 'Tiggo 7 Pro Max', year: 2023, mileage: 14000, price: 2150000, city: 'Москва' },
    city: 'Москва',
    client: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    priceSegment: '2–2.5 млн ₽',
    summary: 'Важно: коробка, шумы подвески, сход-развал',
    expertId: 'evk',
    appointmentAt: '2025-12-02T14:35:00Z',
    createdAt: '2025-12-01T09:40:00Z',
    updatedAt: '2025-12-02T16:10:00Z',
    selectionOrderId: 'POD-0601',
    address: 'Москва, Новоясеневский проезд 15А',
  },
  {
    id: 'OSM-2003',
    status: 'ASSIGNED',
    sourceUrl: 'https://auto.ru/car-geely-monjaro-2022',
    parsedData: { make: 'Geely', model: 'Monjaro', year: 2022, mileage: 28000, price: 2850000, city: 'Химки' },
    city: 'Химки',
    client: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    priceSegment: '2.5–3 млн ₽',
    summary: 'Смотреть вариатор, полный привод, сканер ошибок',
    expertId: 'eva',
    appointmentAt: '2025-12-03T12:00:00Z',
    createdAt: '2025-12-01T10:15:00Z',
    updatedAt: '2025-12-02T15:00:00Z',
    selectionOrderId: 'POD-0602',
    address: 'Химки, Ленинградское шоссе, 5',
  },
  {
    id: 'OSM-2004',
    status: 'WAITING_FOR_EXPERT',
    sourceUrl: 'https://auto.ru/car-haval-jolion-2022',
    parsedData: { make: 'Haval', model: 'Jolion', year: 2022, mileage: 32000, price: 1800000, city: 'Мытищи' },
    city: 'Мытищи',
    client: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    priceSegment: '1.5–2 млн ₽',
    summary: 'Проверить робота/сцепление, коррозию, стекла',
    expertId: null,
    appointmentAt: null,
    createdAt: '2025-12-02T08:45:00Z',
    updatedAt: '2025-12-02T08:45:00Z',
    address: 'Мытищи, Волковское шоссе, 12',
  },
  {
    id: 'OSM-2005',
    status: 'NEW',
    sourceUrl: 'https://auto.ru/car-kia-k5-2021',
    parsedData: { make: 'Kia', model: 'K5', year: 2021, mileage: 45000, price: 2400000, city: 'Москва' },
    city: 'Москва',
    client: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    priceSegment: '2–2.5 млн ₽',
    summary: 'Смотреть окрас, турбину, кондиционер',
    expertId: null,
    appointmentAt: null,
    createdAt: '2025-12-03T09:20:00Z',
    updatedAt: '2025-12-03T09:20:00Z',
    address: 'Москва, ул. Академика Королёва, 10',
  },
  {
    id: 'OSM-2006',
    status: 'IN_PROGRESS',
    sourceUrl: 'https://auto.ru/car-toyota-rav4-2018',
    parsedData: { make: 'Toyota', model: 'RAV4', year: 2018, mileage: 82000, price: 2450000, city: 'Одинцово' },
    city: 'Одинцово',
    client: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    priceSegment: '2–2.5 млн ₽',
    summary: 'Смотреть по кузову, стук рейки, кондиционер',
    expertId: 'denis',
    appointmentAt: '2025-12-03T16:00:00Z',
    createdAt: '2025-12-02T11:00:00Z',
    updatedAt: '2025-12-03T10:10:00Z',
    selectionOrderId: 'POD-0603',
    address: 'Одинцово, Можайское ш., 55',
  },
  {
    id: 'OSM-2007',
    status: 'DONE',
    sourceUrl: 'https://auto.ru/car-bmw-3-2017',
    parsedData: { make: 'BMW', model: '320d', year: 2017, mileage: 92000, price: 2050000, city: 'Москва' },
    city: 'Москва',
    client: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    priceSegment: '2–2.5 млн ₽',
    summary: 'Диагностика дизеля, рулевая, тормоза',
    expertId: 'eva',
    appointmentAt: '2025-11-30T12:30:00Z',
    createdAt: '2025-11-29T15:20:00Z',
    updatedAt: '2025-12-01T09:00:00Z',
    address: 'Москва, ул. Правды, 15',
    report: {
      id: 'REP-1002',
      inspectionOrderId: 'OSM-2007',
      templateId: 'CHK-1',
      data: {
        body: { paint: '110–150 мкм, без вторички', accident: 'no', corrosion: 'no', glass: 'no' },
        engine: { 'engine-sound': 'ok', leaks: 'no', fluids: 'ok', belts: 'Замена ремня через 20 тыс. км' },
        suspension: { transmission: 'ok', 'suspension-noise': 'ok', steering: 'ok', brakes: 'ok' },
        interior: { diagnostics: 'clean', climate: 'ok', multimedia: 'ok', interior: 'Салон ухожен, химчистка не требуется' },
        docs: { 'vin-match': 'ok', owners: 1, service: 'Полная история у дилера' },
        testdrive: { dynamics: 'ok', vibrations: 'no', 'summary-notes': 'Едет ровно, нареканий нет' },
      },
      severities: {},
      summary: 'Рекомендуем: нареканий нет, по кузову и технике без замечаний.',
      recommendedDiscount: { min: 0, max: 20000, comment: 'Торг на расходники' },
      webUrl: 'https://reports.local/OSM-2007',
      pdfUrl: 'https://reports.local/OSM-2007.pdf',
      legalCheck: { pledge: 'OK', restrictions: 'OK', fines: 'OK', ownersCount: 1, notes: 'Ограничений нет' },
    },
  },
  {
    id: 'OSM-2008',
    status: 'CANCELLED',
    sourceUrl: 'https://auto.ru/car-hyundai-solaris-2019',
    parsedData: { make: 'Hyundai', model: 'Solaris', year: 2019, mileage: 67000, price: 1100000, city: 'Москва' },
    city: 'Москва',
    client: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    priceSegment: 'до 1.5 млн ₽',
    summary: 'Клиент передумал, заказ отменён',
    expertId: null,
    appointmentAt: null,
    createdAt: '2025-12-01T08:00:00Z',
    updatedAt: '2025-12-01T10:00:00Z',
    address: 'Москва, ТТК, дилерский центр',
  },
];

const candidateLegalOk: LegalCheck = {
  pledge: 'OK',
  restrictions: 'OK',
  fines: 'OK',
  ownersCount: 1,
  notes: 'ДКП и сервиска в наличии',
};

const candidateLegalRisk: LegalCheck = {
  pledge: 'RISK',
  restrictions: 'RISK',
  fines: 'OK',
  ownersCount: 3,
  notes: 'Есть залог, нужно уточнять погашение',
};

const mockCandidates: Candidate[] = [
  {
    id: 'CAND-201',
    sourceUrl: 'https://auto.ru/car-chery-tiggo7-2023',
    make: 'Chery',
    model: 'Tiggo 7 Pro Max',
    year: 2023,
    body: 'SUV',
    mileage: 14000,
    price: 2150000,
    city: 'Москва',
    status: 'PENDING',
    summary: 'Свежий, 1 владелец, ТО у дилера',
    inspectionId: 'OSM-2002',
    legalCheck: candidateLegalOk,
  },
  {
    id: 'CAND-202',
    sourceUrl: 'https://auto.ru/car-geely-monjaro-2022',
    make: 'Geely',
    model: 'Monjaro',
    year: 2022,
    body: 'SUV',
    mileage: 28000,
    price: 2850000,
    city: 'Химки',
    status: 'PENDING',
    summary: 'Есть вопросы по вариатору, но по ЛКП чисто',
    inspectionId: 'OSM-2003',
    legalCheck: candidateLegalRisk,
  },
  {
    id: 'CAND-203',
    sourceUrl: 'https://auto.ru/car-toyota-rav4-2018',
    make: 'Toyota',
    model: 'RAV4',
    year: 2018,
    body: 'SUV',
    mileage: 82000,
    price: 2450000,
    city: 'Одинцово',
    status: 'APPROVED',
    summary: 'Хорошее состояние, есть мелкие вложения по ходовой',
    inspectionId: 'OSM-2006',
    legalCheck: candidateLegalOk,
  },
  {
    id: 'CAND-204',
    sourceUrl: 'https://auto.ru/car-kia-k5-2021',
    make: 'Kia',
    model: 'K5',
    year: 2021,
    body: 'Sedan',
    mileage: 45000,
    price: 2400000,
    city: 'Москва',
    status: 'REJECTED',
    summary: 'Нет обогрева лобового, дорого',
  },
];

export const mockSelections: SelectionOrder[] = [
  {
    id: 'POD-0601',
    status: 'CANDIDATES_SENT',
    assignedExpertId: 'evk',
    city: 'Москва',
    cityFrom: 'Москва',
    cityTarget: 'Москва и МО',
    client: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    budget: '2.5–3 млн ₽',
    budgetMin: 2500000,
    budgetMax: 3000000,
    requirements: 'Кроссовер, 2020+, до 70 тыс. км, без серьёзных ДТП, автомат',
    deadline: '2025-12-10',
    includedInspections: 5,
    extraInspections: 0,
    tariffId: 'P-SEL-1',
    inspectionIds: ['OSM-2001', 'OSM-2002'],
    candidates: [mockCandidates[0]],
    createdAt: '2025-11-28T10:00:00Z',
    updatedAt: '2025-12-02T16:10:00Z',
  },
  {
    id: 'POD-0602',
    status: 'SOURCING',
    assignedExpertId: 'eva',
    city: 'Химки',
    cityFrom: 'Москва',
    cityTarget: 'МО север',
    client: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    budget: '2.7–3.2 млн ₽',
    budgetMin: 2700000,
    budgetMax: 3200000,
    requirements: 'Полный привод, 2021+, автомат, без тоталов',
    deadline: '2025-12-18',
    includedInspections: 5,
    extraInspections: 1,
    tariffId: 'P-SEL-1',
    inspectionIds: ['OSM-2003'],
    candidates: [mockCandidates[1]],
    createdAt: '2025-12-01T08:30:00Z',
    updatedAt: '2025-12-02T15:00:00Z',
  },
  {
    id: 'POD-0603',
    status: 'INSPECTIONS',
    assignedExpertId: 'denis',
    city: 'Одинцово',
    cityFrom: 'Москва',
    cityTarget: 'Запад МО',
    client: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    budget: '2–2.6 млн ₽',
    budgetMin: 2000000,
    budgetMax: 2600000,
    requirements: 'Кроссовер/паркетник, полный привод по возможности',
    deadline: '2025-12-12',
    includedInspections: 3,
    extraInspections: 1,
    tariffId: 'P-SEL-1',
    inspectionIds: ['OSM-2006'],
    candidates: [mockCandidates[2], mockCandidates[3]],
    createdAt: '2025-11-30T12:00:00Z',
    updatedAt: '2025-12-03T10:10:00Z',
  },
];

export const mockChecklistTemplates: ChecklistTemplate[] = [
  {
    id: 'CHK-1',
    name: 'Базовый чеклист: легковой авто',
    version: '1.1',
    sections: [
      {
        id: 'body',
        title: 'Кузов и ЛКП',
        items: [
          { id: 'paint', label: 'Толщина ЛКП (замеры)', type: 'text', severityEnabled: true },
          {
            id: 'accident',
            label: 'Следы ДТП/ремонт',
            type: 'enum',
            options: [
              { value: 'no', label: 'Не обнаружено' },
              { value: 'minor', label: 'Косметический ремонт' },
              { value: 'serious', label: 'Серьёзные повреждения' },
            ],
            severityEnabled: true,
          },
          { id: 'corrosion', label: 'Коррозия/очаги', type: 'enum', options: [{ value: 'no', label: 'Нет' }, { value: 'surface', label: 'Поверхностная' }, { value: 'structural', label: 'Несущие элементы' }], severityEnabled: true },
          { id: 'glass', label: 'Стёкла/оптика заменялись', type: 'enum', options: [{ value: 'no', label: 'Нет' }, { value: 'partial', label: 'Частично' }, { value: 'yes', label: 'Да' }] },
        ],
      },
      {
        id: 'engine',
        title: 'Двигатель и охлаждение',
        items: [
          { id: 'engine-sound', label: 'Посторонние звуки', type: 'enum', options: [{ value: 'ok', label: 'Нет' }, { value: 'warn', label: 'Есть' }], severityEnabled: true },
          { id: 'leaks', label: 'Подтеки масел/антифриза', type: 'enum', options: [{ value: 'no', label: 'Нет' }, { value: 'minor', label: 'Незначительные' }, { value: 'yes', label: 'Есть' }], severityEnabled: true },
          { id: 'fluids', label: 'Уровни жидкостей', type: 'enum', options: [{ value: 'ok', label: 'OK' }, { value: 'low', label: 'Ниже нормы' }] },
          { id: 'belts', label: 'Ремни/цепь/помпа', type: 'text' },
        ],
      },
      {
        id: 'suspension',
        title: 'Трансмиссия и ходовая',
        items: [
          { id: 'transmission', label: 'Трансмиссия (АКПП/МКПП/вариатор)', type: 'enum', options: [{ value: 'ok', label: 'Ок' }, { value: 'jerk', label: 'Пинки/рывки' }, { value: 'slip', label: 'Пробуксовка' }], severityEnabled: true },
          { id: 'suspension-noise', label: 'Подвеска/шуми', type: 'enum', options: [{ value: 'ok', label: 'Без шумов' }, { value: 'minor', label: 'Есть посторонние звуки' }], severityEnabled: true },
          { id: 'steering', label: 'Рулевое/люфт', type: 'enum', options: [{ value: 'ok', label: 'Норма' }, { value: 'play', label: 'Есть люфт/стук' }], severityEnabled: true },
          { id: 'brakes', label: 'Тормоза', type: 'enum', options: [{ value: 'ok', label: 'Норма' }, { value: 'vibration', label: 'Вибрации' }, { value: 'pull', label: 'Ведёт/увод' }], severityEnabled: true },
        ],
      },
      {
        id: 'interior',
        title: 'Электрика и салон',
        items: [
          { id: 'diagnostics', label: 'Ошибки на сканере', type: 'enum', options: [{ value: 'clean', label: 'Нет ошибок' }, { value: 'minor', label: 'Несистемные' }, { value: 'critical', label: 'Критичные' }] },
          { id: 'climate', label: 'Климат/печка/кондиционер', type: 'enum', options: [{ value: 'ok', label: 'Работает' }, { value: 'weak', label: 'Слабое охлаждение/обогрев' }, { value: 'no', label: 'Не работает' }] },
          { id: 'multimedia', label: 'Мультимедиа/камеры', type: 'enum', options: [{ value: 'ok', label: 'Работает' }, { value: 'partial', label: 'Частично' }, { value: 'no', label: 'Не работает' }] },
          { id: 'interior', label: 'Состояние салона', type: 'text' },
        ],
      },
      {
        id: 'docs',
        title: 'Документы и история',
        items: [
          { id: 'vin-match', label: 'VIN/маркировки совпадают', type: 'enum', options: [{ value: 'ok', label: 'Да' }, { value: 'issue', label: 'Есть вопросы' }] },
          { id: 'owners', label: 'Кол-во владельцев (ПТС)', type: 'number' },
          { id: 'service', label: 'Сервисная история', type: 'text' },
        ],
      },
      {
        id: 'testdrive',
        title: 'Тест-драйв',
        items: [
          { id: 'dynamics', label: 'Динамика/разгон', type: 'enum', options: [{ value: 'ok', label: 'Норма' }, { value: 'sluggish', label: 'Вялая' }, { value: 'issues', label: 'Есть проблемы' }] },
          { id: 'vibrations', label: 'Вибрации/шумы при ходе', type: 'enum', options: [{ value: 'no', label: 'Нет' }, { value: 'yes', label: 'Есть' }] },
          { id: 'summary-notes', label: 'Замечания по пробной поездке', type: 'text' },
        ],
      },
    ],
  },
];

export const mockTariffs: Tariff[] = [
  { id: 'T-1', priceSegment: 'до 1.5 млн ₽', amount: 9000, comment: 'Город внутри МКАД', kind: 'inspection' },
  { id: 'T-2', priceSegment: '1.5–3 млн ₽', amount: 12000, comment: 'Включая выезд до 30 км', kind: 'inspection' },
  { id: 'T-3', priceSegment: '3–5 млн ₽', amount: 'custom', comment: 'По договоренности', kind: 'inspection' },
  { id: 'P-SEL-1', priceSegment: 'Комплексный подбор (5 осмотров)', amount: 45000, comment: 'Базовый пакет 5 осмотров', kind: 'selection' },
  { id: 'P-SEL-2', priceSegment: 'Комплексный подбор (доп. осмотр)', amount: 9000, comment: 'Добавочный осмотр к подбору', kind: 'selection' },
];

export const mockChats: ChatThread[] = [
  {
    id: 'CHAT-POD-0601',
    participant: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    selectionId: 'POD-0601',
    inspectionId: 'OSM-2002',
    messages: [
      { id: 'm0', from: 'system', text: 'Создан подбор POD-0601, прикреплены осмотры OSM-2001 и OSM-2002.', createdAt: '2025-12-01T09:05:00Z' },
      { id: 'm1', from: 'service', text: 'Осмотр по Chery Tiggo 7 назначен на 02.12 14:35, эксперт Евгения К.', createdAt: '2025-12-01T10:00:00Z', actions: [{ label: 'Подтвердить время', reply: 'Время подтверждено, спасибо' }] },
      { id: 'm2', from: 'client', text: 'Подойдёт, жду отчёт.', createdAt: '2025-12-01T10:05:00Z' },
      { id: 'm3', from: 'system', text: 'Отчёт по OSM-2001 готов. Рекомендована скидка 60–90 тыс.', createdAt: '2025-12-02T18:05:00Z', actions: [{ label: 'Открыть отчёт', reply: 'Открыть отчёт по OSM-2001' }] },
    ],
  },
  {
    id: 'CHAT-OSM-2006',
    participant: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    inspectionId: 'OSM-2006',
    selectionId: 'POD-0603',
    messages: [
      { id: 'm4', from: 'client', text: 'Можно перенести RAV4 на завтра?', createdAt: '2025-12-02T12:10:00Z' },
      { id: 'm5', from: 'service', text: 'Денис сможет 03.12 в 16:00. Подойдёт?', createdAt: '2025-12-02T12:20:00Z', actions: [{ label: 'Подтвердить слот', reply: 'Да, подтверждаю 03.12 16:00' }] },
      { id: 'm6', from: 'system', text: 'Статус осмотра OSM-2006: IN_PROGRESS.', createdAt: '2025-12-03T10:10:00Z' },
    ],
  },
  {
    id: 'CHAT-OSM-2007',
    participant: { name: 'Тест Клиент', phone: '+7 (900) 123-45-67' },
    inspectionId: 'OSM-2007',
    messages: [
      { id: 'm7', from: 'system', text: 'Отчёт по OSM-2007 готов. Нареканий нет.', createdAt: '2025-12-01T09:05:00Z', actions: [{ label: 'Открыть отчёт', reply: 'Открыть отчёт по OSM-2007' }] },
      { id: 'm8', from: 'service', text: 'Можем помочь с торгом на расходники.', createdAt: '2025-12-01T09:10:00Z' },
    ],
  },
];
